### ISSUE TITLE
Slow scrolling in modals on Safari

### ISSUE THREAD

**Issue by TimonVS** [codetree/feedback#192]
I noticed that scrolling a modal window is really slow in Safari, and in Chrome it causes another issue:

![](https://i.imgur.com/wlBuQdl.png)

The modal backdrop scrolls away.

A simple fix is to use  `position: fixed` for `.modal-backdrop` instead of `position: absolute`. This will fix the slowness for Safari and the scrolling issue for Chrome.

**Comment by derrickreimer** [comment]
Upgraded Bootstrap modal, looks like these issues were taken care of by latest changes :+1:

**Comment by TimonVS** [comment]
@djreimer the issue seems to be resolved for Chrome, but scrolling is still extremely slow in Safari :/.

**Comment by TimonVS** [comment]
@djreimer could you reopen this issue? It's really frustrating to use Codetree in Safari this way.

**Comment by TimonVS** [comment]
An easy (but dirty) fix would be to add `transform: translate3d(0, 0, 0);` to `.model-dialog` to force GPU rendering.

**Comment by derrickreimer** [comment]
Thanks for sharing a hack! I'll give that a try 👍

**Comment by derrickreimer** [comment]
@TimonVS can you give it another try? I deployed the GPU rendering fix you suggested. Seems fine on my machine (comparable to Chrome). I'm running Safari Version 9.1 (11601.5.17.1).

**Comment by TimonVS** [comment]
@djreimer Still the same problem, and that's because the rule you added (`transform: translate3d(0, 0, 0);`) gets overridden.

![https://i.imgur.com/eJFfFw2.png](https://i.imgur.com/eJFfFw2.png).

Adding `!important` solves the problem.

**Comment by derrickreimer** [comment]
Fixed the specificity problem.
